### ISSUE TITLE
Extension missing from iTop Hub

### ISSUE THREAD

**Issue by athompson-merlin** [TeemIp/teemip-cable-mgmt#2]
I notice that this extension, which seems highly useful, is not available to install through the iTop Hub.  I can install it by hand, of course, but I really prefer not to mix manual and Hub-installed extensions on the same instance.
Any chance of getting this packaged up and deployable through the Hub?

**Comment by xtophe38** [comment]
A package (zip) 1.1.0 should be released within a month or so and it will be available through TeemIp's sites ([wiki](https://wiki.teemip.net), [SourceForge](https://sourceforge.net/projects/teemip/), [www](https://www.teemip.net)). I don't have any date for a publication on iTop's hub though. Probably before the end of the year.
This being said, there is no restriction and no side effects to have at the same time some extensions downloaded from iTop's Hub and some others installed in the extensions/ directory.

**Comment by xtophe38** [comment]
Extension has been published on the Hub today.
