### ISSUE TITLE
Feature Request - Create cable class to connect physical interface to physical interface

### ISSUE THREAD

**Issue by freeblazin** [TeemIp/teemip-cable-mgmt#3]
I love the extension and appreciate all the hard work into developing it.  I am currently limited with the ability to track and view relations of connections from physical interfaces to other physical interfaces.

For example, I have managed switches that connect directly to endpoints or servers with Ethernet cables and would love to be able to see these assets when viewing the "Wiring" relations.

I have set the Physical Interface wiring properties on both sides to document the connection, but this does not populate in the relations view.
```
Server X Physical Interface Port 0
Network socket: <blank>
Remote device: Office Access Switch
Remote physical interface: Office Access Switch GigabitEthernet0/9

Office Access Switch Physical Interface GigabitEthernet0/9
Network socket: <blank>
Remote device: Server X
Remote physical interface: Server X Port 0
```

**Comment by xtophe38** [comment]
Thanks for your comment. I add your legitimate requirement in my to do list for the next revision. I _should_ be able to work on it before the end of summer.

**Comment by xtophe38** [comment]
The extension now proposes Direct Network Cables, a new class that directly connects 2 physical interfaces together. And wiring relations do show such link as well.

Code is already available here and the new revision should be published before the end of the year. Wiki still need to be updated.

I'd appreciate if you could test these new features. Many thanks in advance.
