### ISSUE TITLE
Can't create second direct cable connection between two devices.

### ISSUE THREAD

**Issue by snapet** [TeemIp/teemip-cable-mgmt#6]
Hi,

Thanks for this plugin we really like it.

As mentioned in the title we think there may be a bug in the logic to add "Direct Network Cable Objects. After connecting a cable between a NAS and a switch I fail to enter/connect a second cable in that order (from NAS to switch).
When I select the switch first and then the NAS that works. But we have a third cable running from the NAS to the switch and that's where my luck runs out. There is no way to add a cable to that NAS anymore as we keep getting the error:
**_The object cannot be saved : A cable is already connecting the same network sockets_**

Best regards,
Peter
![Screenshot Direct Network Connection error](https://github.com/user-attachments/assets/376fbc79-b9cc-4fa4-855d-8f94f2b5083b)

**Comment by xtophe38** [comment]
Hello,

Cool to read that you like the extension !

Are you trying to connect your NAS and Switch through the same interfaces or different ones ? Note that, by default, TeemIp considers that only one cable can be attached to a given interface...

**Comment by snapet** [comment]
Hi again,

Through different interfaces or ports on both NAS and switch. That I
wouldn't be able to connect two cables through the same interface makes
perfect sense to me!

cheers,
peter

**Comment by xtophe38** [comment]
Hello,

I managed to reproduce your issue ! I've corrected it and took the opportunity to review and improve the controls done when cables are created. Correction will be part of next revision of the extensio. In the mean time, you may get the updated files here, from GtHub.

Related commit is [this one](https://github.com/TeemIp/teemip-cable-mgmt/commit/de4a1b6d3bf8c719114cae8ddd4486b2c2f36e62).

**Comment by snapet** [comment]
Thank you very much for solving this so quickly!
